name: Publish the mkdocs to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  

    steps:    
    - id: step-7
      name: Deploy docs
      run: mkdocs gh-deploy --force
