name: Publish the mkdocs to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
 release:
    runs-on: ubuntu-latest
    steps:
    - id: step-0
      uses: actions/checkout@v3
    - id: step-3
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - id: step-4
      run: pip install -r docs/requirements.txt
    - id: step-7
      name: Deploy docs
      run: mkdocs gh-deploy --force
